=== PathCalc/pathcalc-web/docs/schemas/public/config/general.schema.json
{
  "type": "object",
  "properties": {
    "logo": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "description": "Primary part of the logotype - displayed in bold"
        },
        "subtitle": {
          "type": "string",
          "description": "Secondary part of the logotype - displayed in a lighter font"
        }
      },
      "required": [
        "title",
        "subtitle"
      ],
      "additionalProperties": false,
      "description": "Logotype configuration for the app."
    },
    "title": {
      "type": "string",
      "description": "Title of the app. Displayed in browser tab title."
    },
    "description": {
      "type": "string",
      "description": "Description of the app. Displayed in social media previews etc."
    },
    "defaultChartSettings": {
      "type": "object",
      "properties": {
        "numberFormat": {
          "type": "object",
          "properties": {},
          "additionalProperties": true,
          "description": "Default number format for the app, following the Intl.NumberFormat options.\nSee https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#options."
        },
        "seriesShapeProps": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {},
            "additionalProperties": true
          },
          "propertyNames": {
            "enum": [
              "line",
              "bar",
              "area"
            ]
          },
          "description": "Default chart series shape properties for each chart type. See docs:\narea: https://recharts.org/en-US/api/Area\nbar: https://recharts.org/en-US/api/Bar\nline: https://recharts.org/en-US/api/Line"
        }
      },
      "required": [
        "numberFormat",
        "seriesShapeProps"
      ],
      "additionalProperties": false,
      "description": "Default settings to apply to all charts."
    }
  },
  "required": [
    "logo",
    "title",
    "description",
    "defaultChartSettings"
  ],
  "additionalProperties": false,
  "description": "General configuration for the app.",
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== PathCalc/pathcalc-web/public/config/general.json
{
    "logo": {
        "title": "PathCalc",
        "subtitle": "Laos"
    },
    "title": "PathCalc Laos",
    "description": "PathCalc visualisation system",
    "defaultChartSettings": {
        "numberFormat": {
            "maximumSignificantDigits": 2,
            "maximumFractionDigits": 1,
            "roundingPriority": "lessPrecision"
        },
        "seriesShapeProps": {
            "area": {
                "stroke": "#000",
                "strokeWidth": 1
            },
            "line": {
                "strokeWidth": 2
            },
            "bar": {
                "stroke": "#000",
                "barSize": 70
            }
        }
    }
}
